# Usar una imagen base de Node.js para construir la aplicación Angular
FROM node:18-alpine AS build

# Crear un directorio de trabajo
WORKDIR /app

# Copiar los archivos de configuración y dependencias
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código de la aplicación
COPY . .

# Construir la aplicación Angular para producción
RUN npm run build --prod

# Usar una imagen base de NGINX para servir la aplicación Angular
FROM nginx:alpine

# Copiar los archivos construidos de Angular a la carpeta por defecto de NGINX
COPY --from=build /app/dist/tu-nombre-aplicacion /usr/share/nginx/html

# Exponer el puerto 4200
EXPOSE 4200
